config/routes.rb
Rails.application.routes.draw do
  resources :det_ordens
  resources :ordenes
  resources :productos
  resources :clientes
  #get '/clientes', to:'clientes#index'
  #get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html	  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root :to => "home#index"	  root :to => "home#index"
  #	  match '/saludo', :to => 'home#saludo', :via => [:get]

  get 'clientes/index'
  root :to => "clientes#index"
  match '/clientes', :to => 'clientes#index', :via =>[:get]
end

app/models/det_orden.rb
class DetOrden < ApplicationRecord
    has_many :ordene
    
end

app/controllers/det_ordens_controller.rb
class DetOrdensController < ApplicationController
  before_action :set_det_orden, only: [:show, :edit, :update, :destroy]

  # GET /det_ordens
  # GET /det_ordens.json
  def index
    @det_ordens = DetOrden.all
  end

  # GET /det_ordens/1
  # GET /det_ordens/1.json
  def show
  end

  # GET /det_ordens/new
  def new
    @det_orden = DetOrden.new
  end

  # GET /det_ordens/1/edit
  def edit
  end

  # POST /det_ordens
  # POST /det_ordens.json
  def create
    @det_orden = DetOrden.new(det_orden_params)

    respond_to do |format|
      if @det_orden.save
        format.html { redirect_to @det_orden, notice: 'Det orden was successfully created.' }
        format.json { render :show, status: :created, location: @det_orden }
      else
        format.html { render :new }
        format.json { render json: @det_orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /det_ordens/1
  # PATCH/PUT /det_ordens/1.json
  def update
    respond_to do |format|
      if @det_orden.update(det_orden_params)
        format.html { redirect_to @det_orden, notice: 'Det orden was successfully updated.' }
        format.json { render :show, status: :ok, location: @det_orden }
      else
        format.html { render :edit }
        format.json { render json: @det_orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /det_ordens/1
  # DELETE /det_ordens/1.json
  def destroy
    @det_orden.destroy
    respond_to do |format|
      format.html { redirect_to det_ordens_url, notice: 'Det orden was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_det_orden
      @det_orden = DetOrden.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def det_orden_params
      params.require(:det_orden).permit(:id_prod, :cantidad, :precio)
    end
end

app/helpers/det_ordens_helper.rb
module DetOrdensHelper
end

app/views/det_ordens/_form.html.erb
<%= form_with(model: det_orden, local: true) do |form| %>
  <% if det_orden.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(det_orden.errors.count, "error") %> prohibited this det_orden from being saved:</h2>

      <ul>
      <% det_orden.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_prod %>
    <%= form.number_field :id_prod %>
  </div>

  <div class="field">
    <%= form.label :cantidad %>
    <%= form.number_field :cantidad %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/det_ordens/edit.html.erb
<h1>Editing Det Orden</h1>

<%= render 'form', det_orden: @det_orden %>

<%= link_to 'Show', @det_orden %> |
<%= link_to 'Back', det_ordens_path %>

app/views/det_ordens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Det Ordens</h1>

<table>
  <thead>
    <tr>
      <th>Id prod</th>
      <th>Cantidad</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @det_ordens.each do |det_orden| %>
      <tr>
        <td><%= det_orden.id_prod %></td>
        <td><%= det_orden.cantidad %></td>
        <td><%= det_orden.precio %></td>
        <td><%= link_to 'Show', det_orden %></td>
        <td><%= link_to 'Edit', edit_det_orden_path(det_orden) %></td>
        <td><%= link_to 'Destroy', det_orden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Det Orden', new_det_orden_path %>

app/views/det_ordens/new.html.erb
<h1>New Det Orden</h1>

<%= render 'form', det_orden: @det_orden %>

<%= link_to 'Back', det_ordens_path %>

app/views/det_ordens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id prod:</strong>
  <%= @det_orden.id_prod %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @det_orden.cantidad %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @det_orden.precio %>
</p>

<%= link_to 'Edit', edit_det_orden_path(@det_orden) %> |
<%= link_to 'Back', det_ordens_path %>