config/routes.rb
Rails.application.routes.draw do
  resources :det_ordens
  resources :ordenes
  resources :productos
  resources :clientes
  #get '/clientes', to:'clientes#index'
  #get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html	  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root :to => "home#index"	  root :to => "home#index"
  #	  match '/saludo', :to => 'home#saludo', :via => [:get]

  get 'clientes/index'
  root :to => "clientes#index"
  match '/clientes', :to => 'clientes#index', :via =>[:get]
end

app/models/ordene.rb
class Ordene < ApplicationRecord
    has_many :productos
    belongs :cliente
end

app/controllers/ordenes_controller.rb
class OrdenesController < ApplicationController
  before_action :set_ordene, only: [:show, :edit, :update, :destroy]

  # GET /ordenes
  # GET /ordenes.json
  def index
    @ordenes = Ordene.all
  end

  # GET /ordenes/1
  # GET /ordenes/1.json
  def show
  end

  # GET /ordenes/new
  def new
    @ordene = Ordene.new
  end

  # GET /ordenes/1/edit
  def edit
  end

  # POST /ordenes
  # POST /ordenes.json
  def create
    @ordene = Ordene.new(ordene_params)

    respond_to do |format|
      if @ordene.save
        format.html { redirect_to @ordene, notice: 'Ordene was successfully created.' }
        format.json { render :show, status: :created, location: @ordene }
      else
        format.html { render :new }
        format.json { render json: @ordene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordenes/1
  # PATCH/PUT /ordenes/1.json
  def update
    respond_to do |format|
      if @ordene.update(ordene_params)
        format.html { redirect_to @ordene, notice: 'Ordene was successfully updated.' }
        format.json { render :show, status: :ok, location: @ordene }
      else
        format.html { render :edit }
        format.json { render json: @ordene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordenes/1
  # DELETE /ordenes/1.json
  def destroy
    @ordene.destroy
    respond_to do |format|
      format.html { redirect_to ordenes_url, notice: 'Ordene was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordene
      @ordene = Ordene.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ordene_params
      params.require(:ordene).permit(:id_c, :nOrden, :fecha)
    end
end

app/helpers/ordenes_helper.rb
module OrdenesHelper
end

app/views/ordenes/_form.html.erb
<%= form_with(model: ordene, local: true) do |form| %>
  <% if ordene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ordene.errors.count, "error") %> prohibited this ordene from being saved:</h2>

      <ul>
      <% ordene.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_c %>
    <%= form.number_field :id_c %>
  </div>

  <div class="field">
    <%= form.label :nOrden %>
    <%= form.number_field :nOrden %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ordenes/edit.html.erb
<h1>Editing Ordene</h1>

<%= render 'form', ordene: @ordene %>

<%= link_to 'Show', @ordene %> |
<%= link_to 'Back', ordenes_path %>

app/views/ordenes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ordenes</h1>

<table>
  <thead>
    <tr>
      <th>Id c</th>
      <th>Norden</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordenes.each do |ordene| %>
      <tr>
        <td><%= ordene.id_c %></td>
        <td><%= ordene.nOrden %></td>
        <td><%= ordene.fecha %></td>
        <td><%= link_to 'Show', ordene %></td>
        <td><%= link_to 'Edit', edit_ordene_path(ordene) %></td>
        <td><%= link_to 'Destroy', ordene, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ordene', new_ordene_path %>

app/views/ordenes/new.html.erb
<h1>New Ordene</h1>

<%= render 'form', ordene: @ordene %>

<%= link_to 'Back', ordenes_path %>

app/views/ordenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id c:</strong>
  <%= @ordene.id_c %>
</p>

<p>
  <strong>Norden:</strong>
  <%= @ordene.nOrden %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @ordene.fecha %>
</p>

<%= link_to 'Edit', edit_ordene_path(@ordene) %> |
<%= link_to 'Back', ordenes_path %>